name: test
on: push

jobs:
  test-tauri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: ⚡ Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          src-tauri/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: tests
      run: cargo test --manifest-path=src-tauri/Cargo.toml

  test-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install
      run: npm install --prefix ui 
    - name: test
      run: npm test
