name: test
on: push

jobs:
  test-tauri:
    runs-on: ubuntu-stable
    steps:
    - uses: actions/checkout@v2
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: tests
      run: cargo test --manifest-path=src-tauri/Cargo.toml
  test-ui:
    runs-on: ubuntu-stable
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: tests
      run: yarn test
